# Generated by Django 3.1.7 on 2021-03-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platomodel',
            table='t_plato',
        ),
    ]
