# Generated by Django 3.1.7 on 2021-03-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_auto_20210324_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalmodel',
            old_name='personaApellido',
            new_name='personalApellido',
        ),
        migrations.RenameField(
            model_name='personalmodel',
            old_name='personaNombre',
            new_name='personalNombre',
        ),
    ]
