# Generated by Django 3.1.7 on 2021-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_auto_20210324_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platomodel',
            name='platoFoto',
            field=models.ImageField(db_column='plato_foto', upload_to='platos/', verbose_name='Foto del plato'),
        ),
    ]
