# Generated by Django 3.1.7 on 2021-03-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_auto_20210325_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesamodel',
            name='mesaNumero',
            field=models.CharField(db_column='mesa_numero', default='1', max_length=10, verbose_name='Numero de mesa'),
            preserve_default=False,
        ),
    ]
