# Generated by Django 3.1.7 on 2021-03-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0011_auto_20210328_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalMesaModel',
        ),
    ]
