# Generated by Django 3.1.7 on 2021-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_especiemodel_especieestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiemodel',
            name='especieId',
            field=models.AutoField(auto_created=True, db_column='especie_id', primary_key=True, serialize=False, unique=True),
        ),
    ]
